services:
#    enguys_core.example:
#        class: Enguys\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    enguys_core.manager.page:
        class: Enguys\CoreBundle\Manager\PageManager
        arguments: ['@request_stack']
    enguys_core.form.type.tags:
        class: Enguys\CoreBundle\Form\Type\TagsType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }
    enguys_core.form.type.media_upload:
        class: Enguys\CoreBundle\Form\Type\MediaUploadType
        arguments: ['@doctrine.orm.entity_manager', '@router']
        tags:
            - { name: form.type }
    enguys_core.templating.core:
        class: Enguys\CoreBundle\Templating\EnguysCoreExtension
        arguments: ['@enguys_core.manager.page']
        tags:
            - { name: 'twig.extension' }
