services:
#    enguys_core.example:
#        class: Enguys\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    enguys_core.manager.page:
        class: Enguys\CoreBundle\Manager\PageManager
        arguments: ['@request_stack']
    enguys_core.form.type.tags:
        class: Enguys\CoreBundle\Form\Type\TagsType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }
